holiday = "Thanksgiving"
actor = "Adam Sandler"
actorTwo = "Also Adam Sandler"
holidayTwo = "Hanukkah"
name = "Jack"
nameTwo = "Jill"
adjective = "happy"
relation = "twin sister"
verb = "dreads"
bodyPart = "foot"
print (holiday + " is usually a " + adjective + " time, but ad executive Jack (" + actor + ") " + verb + " the holiday because his " + relation + ", Jill (" + actorTwo + "), makes her annual visit. When Jack and his sister get off on the wrong " + bodyPart + ", the only way to make it right is to invite her to stay through " + holidayTwo + ".")